spring:
  application:
    name: camundaSwagger

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

zeebe:
  client:
    broker:
      gateway-address: "http://127.0.0.1:26500"
    security:
      plaintext: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


