package dev.rugved.camundaSwagger.dto;

public record ErrorResponse(String errorCode, String error, String errorDescription) {
    // Any additional methods can be added here, but the default constructor and getters
    // are automatically generated by the record feature

    // If you need validation, you can add a compact constructor
    public ErrorResponse {
        // Validation logic can go here (if needed)
        if (errorCode == null) {
            errorCode = "UNKNOWN";
        }
    }

    // You can also add static factory methods
    public static ErrorResponse of(String errorCode, String error) {
        return new ErrorResponse(errorCode, error, null);
    }
}